### ISSUE TITLE
Rescanning the Address throws error

### ISSUE THREAD

**Issue by devesh-aggrawal** [mmgen/mmgen-wallet#13]
Hi Team,

I have created a new wallet and imported the same wallet addresses to make the addresses trackable. I moved a small amount of bitcoin to the first SEGWIT address created. The transaction is visible on the blockchain but when I check using mmgen cli command (mmgen-tool listaddresses), it is not showing the balance. 

> Getting unspent outputs...done
Getting labels and associated addresses...done
Getting received funds data...done
TRACKING WALLET ADDRESSES (sort order: MMGenID)
Filters: showempty:yes showused:yes all_labels:no
Network: BTC MAINNET
Block 857893 [2024-08-22 09:56:23]
Total BTC: 0
Displaying balances with at least 1 confirmation

     MMGenID       Used Address                            Comment Balance    Confs
  1) 4A087EEC:S:1  No   38g4JXU6wy3wspRVBXD2TXotnDvoPu41zH -       0          -
  2) 4A087EEC:S:2  No   3HesqEfxch3inMrzyrwwueTRbyhYXUAorB -       0          -
  3) 4A087EEC:S:3  No   3GqNYdtbQMsgrZXwFw98qVXussL8bsrace -       0          -
  4) 4A087EEC:S:4  No   3CvUT2bzFHJtJcYFVBDpmW9GcJq9sVh5Px -       0          -
  5) 4A087EEC:S:5  No   3543ZDKWfzvt8BwSDcqiqd2niat6JQxcDY -       0          -
  6) 4A087EEC:S:6  No   37A982i7LV5fYT5uesozgJ1JAjeZpbX7PB -       0          -
  7) 4A087EEC:S:7  No   3QawpdaeQb9sd8qMqxUeU9MgAmPeSVpkxb -       0          -
  8) 4A087EEC:S:8  No   3L8Sh4vFiZSLxWWgTK5SkEz4tAUM6ygdbH -       0          -
  9) 4A087EEC:S:9  No   38gL4oy3nFSeDGwV78yvqCqH5YoofzMjh5 -       0          -
 10) 4A087EEC:S:10 No   3E7gV5TmJ85AyKiZdWWN6ivniLX5dv38Jj -       0          -

> TOTAL: 0 BTC

I tried to rescan the address using the mmgen cli(mmgen-tool rescan_address ) but then wallet is not able to run the command and throws error before completing.

>(env) ubuntu@ip-172-31-33-6:~$ mmgen-tool rescan_address 38g4JXU6wy3wspRVBXD2TXotnDvoPu41zH
Aborting scan in progress...done
Scanning UTXO set, this could take several minutes...
MMGen Error (RPCFailure):
timed out

Can you please help me understand what is the problem here.

**Comment by mmgen** [comment]
The address indeed has a balance and was spent to in block 857799.

If you imported the address before your node synced to block 857799, `listaddresses` should have shown the balance, even without the address rescan.

What platform are you running on (hardware, memory, OS version), and what version of Bitcoin Core and MMGen are you running?

**Comment by devesh-aggrawal** [comment]
Bitcoin core and mmgen wallets are on two different servers but in the same VPC in AWS. I'm using mmgen.cfg to configure the rpc_host, rpc_port, rpc_user and rpc_password and able to connect to bitcoin core. 

MMGEN server is a  Ubuntu 24.04 LTS server running on an AWS EC2 instance. The current version of MMGEN-TOOL is 14.1.1

Bitcoin Core server is a  Ubuntu 18.04.4 LTS server running on an AWS EC2 instance. The current version of Bitcoin Core RPC client is v0.21.1.

**Comment by mmgen** [comment]
There are two things that you might look into here:
- your bitcoind version is old, try upgrading
- you have too little memory on the instance running MMGen Wallet. I've had problems with 4GB RAM or less

You might try running MMGen Wallet on your local machine and connecting to the bitcoind using SSH forwarding.

**Comment by devesh-aggrawal** [comment]
I'll check the recommendations. Also can you help me understand the commands I need to follow, if I have a 12 letters seed and want to import in a MMGen Wallet. Can you please help me with it

**Comment by mmgen** [comment]
You can either enter the seed phrase manually:

    mmgen-walletconv -i bip39

or put the words in a file with a `.bip39` extension:

    mmgen-walletconv seed.bip39
