### ISSUE TITLE
Mac OS Install

### ISSUE THREAD

**Issue by xpnewmedia** [mmgen/mmgen-wallet#8]
How to install on Big Sur 11.4 (20F71)
M1 Chip

Thanks

**Comment by mmgen** [comment]
MMGen doesn't support Mac OS (yet), though support will be added in the future if we receive enough requests for it. I'll leave this issue open for that purpose.

**Comment by mmgen** [comment]
Full macOS support added: bcff2e4f

    $ brew install libtool libmpc autoconf bash coreutils secp256k1

Then follow the Linux install instructions in the Wiki

Your comments are welcome!

**Comment by mmgen** [comment]
macOS support now official: https://github.com/mmgen/mmgen-wallet/releases/tag/v15.0.0

https://github.com/mmgen/mmgen-wallet/wiki/Install-MMGen-Wallet-on-Linux-or-macOS
